### ISSUE TITLE
Add requirements.txt

### ISSUE THREAD

**Issue by PirulaxWork** [LinkReincarnate/PythonSoundboard#4]
Should add requirements.txt, as pygame is a dependency, and it would be nicer if users would just have to install it using requirements.txt

**Comment by LinkReincarnate** [comment]
is there a certain format that needs to be in or is it just a list of libraries?

**Comment by PirulaxWork** [comment]
This issue is mostly just a note for myself, but yeah, it's just a simple txt file.
For us it will do.
I'll create one.
